//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :2.0.50727.4927
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Synchronisation {
    
    
    public partial class EurequatCacheClientSyncProvider : Microsoft.Synchronization.Data.SqlServerCe.SqlCeClientSyncProvider {
        
        public EurequatCacheClientSyncProvider() {
            this.ConnectionString = ("Data Source=" 
                        + (System.IO.Path.Combine(System.IO.Path.GetDirectoryName(System.Reflection.Assembly.GetExecutingAssembly().GetName().CodeBase), "Eurequat.sdf") + ";Max Database Size=2047"));
        }
        
        public EurequatCacheClientSyncProvider(string connectionString) {
            this.ConnectionString = connectionString;
        }
    }
    
    public partial class EurequatCacheSyncAgent : Microsoft.Synchronization.SyncAgent {
        
        private personneSyncTable _personneSyncTable;
        
        partial void OnInitialized();
        
        public EurequatCacheSyncAgent() {
            this.InitializeSyncProviders();
            this.InitializeSyncTables();
            this.OnInitialized();
        }
        
        public EurequatCacheSyncAgent(object remoteSyncProviderProxy) {
            this.InitializeSyncProviders();
            this.InitializeSyncTables();
            this.RemoteProvider = new Microsoft.Synchronization.Data.ServerSyncProviderProxy(remoteSyncProviderProxy);
            this.OnInitialized();
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public personneSyncTable personne {
            get {
                return this._personneSyncTable;
            }
            set {
                this.Configuration.SyncTables.Remove(this._personneSyncTable);
                this._personneSyncTable = value;
                this.Configuration.SyncTables.Add(this._personneSyncTable);
            }
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void InitializeSyncProviders() {
            // Create SyncProviders.
            this.LocalProvider = new EurequatCacheClientSyncProvider();
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void InitializeSyncTables() {
            // Create SyncTables.
            this._personneSyncTable = new personneSyncTable();
            this._personneSyncTable.SyncGroup = new Microsoft.Synchronization.Data.SyncGroup("personneSyncTableSyncGroup");
            this.Configuration.SyncTables.Add(this._personneSyncTable);
        }
        
        public partial class personneSyncTable : Microsoft.Synchronization.Data.SyncTable {
            
            partial void OnInitialized();
            
            public personneSyncTable() {
                this.InitializeTableOptions();
                this.OnInitialized();
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            private void InitializeTableOptions() {
                this.TableName = "personne";
                this.CreationOption = Microsoft.Synchronization.Data.TableCreationOption.DropExistingOrCreateNewTable;
            }
        }
    }
}
